"""Add venue URL & phone number columns

Revision ID: 3b333b42a855
Revises: eeba71363d2d
Create Date: 2019-05-26 16:56:10.324280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b333b42a855'
down_revision = 'eeba71363d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('phone_number', sa.String(),
                                      nullable=True))
    op.add_column('venues', sa.Column('web_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'web_url')
    op.drop_column('venues', 'phone_number')
    # ### end Alembic commands ###
