"""Make address2 nullable

Revision ID: c9bca9907ca7
Revises: 3b333b42a855
Create Date: 2019-05-26 17:35:30.009593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bca9907ca7'
down_revision = '3b333b42a855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues') as batch_op:
        batch_op.drop_column('address2')
        batch_op.add_column(sa.Column('address2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues') as batch_op:
        batch_op.add_column('venues', sa.Column('address2', sa.String(),
                            nullable=False))
        batch_op.drop_column('address2')
    # ### end Alembic commands ###
